language: php
dist: bionic

matrix:
  include:
    - php: 5.6
      dist: trusty
      env: PHPUNIT=5.7
    - php: 7.0
      dist: xenial
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
  - composer install
  - if [[ $PHPUNIT == 5.7 ]]; then composer require "phpunit/phpunit:5.7"; fi

script:
  - |
    if [[ $PHPUNIT == 5.7 ]]; then
      ./vendor/bin/phpunit .
    else
      phpunit .
    fi
